// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TextUIClient is the client API for TextUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TextUIClient interface {
	// ListEngineSpecs returns a list of Text Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (TextUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type textUIClient struct {
	cc grpc.ClientConnInterface
}

func NewTextUIClient(cc grpc.ClientConnInterface) TextUIClient {
	return &textUIClient{cc}
}

func (c *textUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (TextUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &TextUI_ServiceDesc.Streams[0], "/v1.TextUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &textUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TextUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type textUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *textUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *textUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.TextUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TextUIServer is the server API for TextUI service.
// All implementations must embed UnimplementedTextUIServer
// for forward compatibility
type TextUIServer interface {
	// ListEngineSpecs returns a list of Text Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, TextUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedTextUIServer()
}

// UnimplementedTextUIServer must be embedded to have forward compatible implementations.
type UnimplementedTextUIServer struct {
}

func (UnimplementedTextUIServer) ListEngineSpecs(*ListEngineSpecsRequest, TextUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedTextUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedTextUIServer) mustEmbedUnimplementedTextUIServer() {}

// UnsafeTextUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TextUIServer will
// result in compilation errors.
type UnsafeTextUIServer interface {
	mustEmbedUnimplementedTextUIServer()
}

func RegisterTextUIServer(s grpc.ServiceRegistrar, srv TextUIServer) {
	s.RegisterService(&TextUI_ServiceDesc, srv)
}

func _TextUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TextUIServer).ListEngineSpecs(m, &textUIListEngineSpecsServer{stream})
}

type TextUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type textUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *textUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _TextUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TextUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.TextUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TextUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TextUI_ServiceDesc is the grpc.ServiceDesc for TextUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TextUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.TextUI",
	HandlerType: (*TextUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _TextUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _TextUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "text-ui.proto",
}
